Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using webdev_consultationPhotovoltaique.Models.photovoltaiqueDB;

namespace webdev_consultationPhotovoltaique.Controllers
{
    public class ServicesController : Controller
    {
        private readonly PhotovoltaiqueDbContext _context;

        public ServicesController(PhotovoltaiqueDbContext context)
        {
            _context = context;
        }

        public IActionResult Profil()
        {
            return View();
        }
        public IActionResult ServiceView()
        {
            return View();
        }
        // GET: Services
        public async Task<IActionResult> Index()
        {
            var photovoltaiqueDbContext = _context.Services.Include(s => s.Entreprise);
            return View(await photovoltaiqueDbContext.ToListAsync());
        }

        // GET: Services/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var service = await _context.Services
                .Include(s => s.Entreprise)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }

        // GET: Services/Create
        public IActionResult Create()
        {
            ViewData["EntrepriseId"] = new SelectList(_context.Entreprises, "Id", "Adresse");
            return View();
        }

        // POST: Services/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EntrepriseId,Id,type,AutreService")] Service service)
        {
            if (ModelState.IsValid)
            {
                _context.Add(service);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EntrepriseId"] = new SelectList(_context.Entreprises, "Id", "Adresse", service.EntrepriseId);
            return View(service);
        }

        // GET: Services/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var service = await _context.Services.FindAsync(id);
            if (service == null)
            {
                return NotFound();
            }
            ViewData["EntrepriseId"] = new SelectList(_context.Entreprises, "Id", "Adresse", service.EntrepriseId);
            return View(service);
        }

        // POST: Services/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EntrepriseId,Id,type,AutreService")] Service service)
        {
            if (id != service.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(service);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServiceExists(service.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EntrepriseId"] = new SelectList(_context.Entreprises, "Id", "Adresse", service.EntrepriseId);
            return View(service);
        }

        // GET: Services/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var service = await _context.Services
                .Include(s => s.Entreprise)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var service = await _context.Services.FindAsync(id);
            if (service != null)
            {
                _context.Services.Remove(service);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ServiceExists(int id)
        {
            return _context.Services.Any(e => e.Id == id);
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.ConstrainedExecution;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using webdev_consultationPhotovoltaique.Models.photovoltaiqueDB;

namespace webdev_consultationPhotovoltaique.Controllers
{
    public class UsersController : Controller
    {
        private readonly PhotovoltaiqueDbContext _context;
        private readonly IHttpContextAccessor _contextAccessor;

        public UsersController(PhotovoltaiqueDbContext context, IHttpContextAccessor contextAccessor)
        {
            _context = context;
            _contextAccessor = contextAccessor;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult RegisterUser()
        {
            return View();
        }
        

        // POST: Users/Create
        [HttpPost]
        public ActionResult Create(User user)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Users.Add(user);
                    _context.SaveChanges();
                    _contextAccessor.HttpContext.Session.SetString("UserEmail", user.Email);
                    _contextAccessor.HttpContext.Session.SetString("MotDePasse", user.MotDePasse); // Assuming you have a Nom property
                                                                                                   // Redirect to a different action or return a success message
                    return RedirectToAction("Index", "Home"); // Redirects to Home/Index
                }
                catch (Exception ex)
                {
                    // Log the exception (you can use a logging framework here)
                    var innerException = ex.InnerException?.Message;
                    ViewBag.ErrorMessage = innerException;
                    // Optionally, you can display this error message in the view
                    ModelState.AddModelError("", "Unable to save changes: " + innerException);
                }
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nom,Prénom,Adresse,Télephone,Gouvernourat,Email,MotDePasse")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
        [HttpGet]
        public ActionResult LoginUser()
        {
            
            return View();
        }
        [HttpPost]
        public ActionResult LoginUser(User user)
        {
           
                // Handle the login logic here
                // For example, you can check the credentials against the database
                var userEmail = user.Email;
                var userPassword = user.MotDePasse;
                // Assuming you have a method to validate user credentials
                var isValidUser = ValidateUserCredentials(userEmail, userPassword);

                if (isValidUser)
                {
                _contextAccessor.HttpContext.Session.SetString("UserEmail", user.Email);
                _contextAccessor.HttpContext.Session.SetString("MotDePasse",user.MotDePasse); // Assuming you have a Nom property
                // Redirect to a different action or return a success message
                return RedirectToAction("Index", "Home"); // Redirects to Home/Index
            }
                else
                {
                    // Add an error message to the model state
                    return RedirectToAction("LoginUser");
                }
           
        }

        private bool ValidateUserCredentials(string email, string password)
        {
            // Query the database for a user with the provided email and password
            var user = _context.Users
                               .FirstOrDefault(u => u.Email == email && u.MotDePasse == password);
            
          
                var entreprise = _context.Entreprises
                               .FirstOrDefault(u => u.Email == email && u.MotDePasse == password);
            if (entreprise != null)
            {
                _contextAccessor.HttpContext.Session.SetString("mat", entreprise.ChampMatricule);
            }

            // Return true if a matching user is found, otherwise false
            return user != null || entreprise !=null;
        }
       

        

    }
}

Views/Shared/Create.cshtml
@model webdev_consultationPhotovoltaique.Models.photovoltaiqueDB.User

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prénom" class="control-label"></label>
                <input asp-for="Prénom" class="form-control" />
                <span asp-validation-for="Prénom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Télephone" class="control-label"></label>
                <input asp-for="Télephone" class="form-control" />
                <span asp-validation-for="Télephone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gouvernourat" class="control-label"></label>
                <input asp-for="Gouvernourat" class="form-control" />
                <span asp-validation-for="Gouvernourat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MotDePasse" class="control-label"></label>
                <input asp-for="MotDePasse" class="form-control" />
                <span asp-validation-for="MotDePasse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crée" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor context;
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="~/css/csslayout2.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <title>Evo-energy</title>
</head>

<body>
    <div id="scrollable-content">
        <div class="wrappershared">
            <nav class="nav">
                <div class="nav-logo">
                    <p> Evo-energy</p>
                </div>
                <div class="nav-menu" id="navMenu">
                    <ul>
                        @if ( context.HttpContext.Session.GetString("mat") != null)
                        {
                            <li><a href="@Url.Action("Index", "Home")" class="link">Home</a></li>
                            <li><a href="@Url.Action("produitView", "produits")" class="link">Ajouter produit</a></li>
                            <li><a href="@Url.Action("ServiceView", "Services")" class="link">Ajouter Service</a></li>
                            <li><a href="@Url.Action("listeproduit", "produits")" class="link">Produits</a></li>
                            <li><a href="@Url.Action("EntrepriseView", "Entreprises")" class="link">Entreprises</a></li>
                            <li><a href="@Url.Action("about1","Home")" class="link">à propos</a></li>
                            <li><a href="@Url.Action("profil","Home")" class="link">Profil</a></li>
                        }

                        else
                       
                       
                        {
                            <li><a href="@Url.Action("Index", "Home")" class="link">Home</a></li>
                            <li><a href="@Url.Action("listeproduit", "produits")" class="link">Produits</a></li>
                            <li><a href="@Url.Action("EntrepriseView", "Entreprises")" class="link">Entreprises</a></li>
                            <li><a href="@Url.Action("feedback", "Home")" class="feed">Ajouter un avis</a></li>
                            <li><a href="@Url.Action("about1","Home")" class="link">À propos</a></li>
                          
                        }
                        
                       
                        
                    </ul>
                </div>               
               <div class="nav-button">
                @if (context.HttpContext.Session.GetString("UserEmail")!=null)
                {
                        <p5>@context.HttpContext.Session.GetString("UserEmail")</p5>
                    <a href="@Url.Action("Logout")" class="btn btn-primary">Déconnexion</a>
                }
                else
                { 
                    <input type="submit" id="loginBtn" onclick="redirectToLogin()" class="button-46" value="Connexion"> 
                    <input type="submit" id="registerBtn" onclick="redirectToRegister()" class="button-46" value="S'inscrire" >
                }
                    </div>
                </div>
               
            </nav>
        </div>
    </div>

    <!-- JavaScript files -->
    <script src="~/js/test.js"></script>
    <script src="~/js/login register.js"></script>
    <script>
        function myMenuFunction() {
            var i = document.getElementById("navMenu");

            if (i.className === "nav-menu") {
                i.className += " responsive";
            } else {
                i.className = "nav-menu";
            }
        }
        function redirectToLogin() {
            window.location.href = '@Url.Action("LoginUser", "Users")';
        }

        function redirectToRegister() {
            window.location.href = '@Url.Action("RegisterUser", "Users")';
        }
    </script>
</body>

</html>

@RenderSection("styles", required: false) <!-- Additional styles from views -->
@RenderBody() <!-- Main content from views -->
@RenderSection("scripts", required: false) <!-- Additional scripts from views -->