Models/photovoltaiqueDB/User.cs
using System.ComponentModel.DataAnnotations;

namespace webdev_consultationPhotovoltaique.Models.photovoltaiqueDB
{
    public class User
    {
        public int Id { get; set; }
       

        
           

            
            [Required(ErrorMessage = "Ce champ est obligatoire")]
            [StringLength(20, MinimumLength = 3, ErrorMessage = "Le longueur de nom est compris entre 3 et 20")]
            public string Nom { get; set; }
            [Required(ErrorMessage = "Ce champ est obligatoire")]
            [StringLength(20, MinimumLength = 3, ErrorMessage = "Le longueur de prénom est compris entre 3 et 20")]
            public string Prénom { get; set; }

            [Required(ErrorMessage = "Ce champ est obligatoire")]
            [StringLength(20, MinimumLength = 3, ErrorMessage = "Le longueur de l'adresse est compris entre 3 et 20")]


            public string Adresse { get; set; }
            [Required(ErrorMessage = "Ce champ est obligatoire")]
            [StringLength(8, MinimumLength = 8, ErrorMessage = "Le longueur du numéro de télephone est 8 numéro")]
            public string Télephone { get; set; }

            public string Gouvernourat { get; set; }
            
        
    




    [Required(ErrorMessage = "Ce champ est obligatoire")]
       
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Ce champ est obligatoire")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Le longueur de Mot de passe est compris entre 3 et 20")]

        public string MotDePasse { get; set; }






    }
}

Controllers/EntreprisesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using webdev_consultationPhotovoltaique.Models.photovoltaiqueDB;

namespace webdev_consultationPhotovoltaique.Controllers
{
    public class EntreprisesController : Controller
    {
        private readonly PhotovoltaiqueDbContext _context;
        private readonly IHttpContextAccessor _contextAccessor;
        public EntreprisesController(PhotovoltaiqueDbContext context, IHttpContextAccessor contextAccessor)
        {
            _context = context;
            _contextAccessor = contextAccessor;
        }

        // GET: Entreprises
        public async Task<IActionResult> Index()
        {
            return View(await _context.Entreprises.ToListAsync());
        }
        public IActionResult EntrepriseView()
        {
            return View();
        }
        public IActionResult DETAILENTREPRISE()
        {
            return View();
        }
        public IActionResult RegisterEntreprise()
        {
            return View();
        }
        // GET: Entreprises/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entreprise = await _context.Entreprises
                .FirstOrDefaultAsync(m => m.Id == id);
            if (entreprise == null)
            {
                return NotFound();
            }

            return View(entreprise);
        }

        // GET: Entreprises/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Entreprises/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nom,Email,Facebook,Instagram,officiel,MotDePasse,Adresse,Gouvernourat,tel,tel2,ChampMatricule")] Entreprise entreprise)
        {
            if (ModelState.IsValid)
            {
                _context.Add(entreprise);
                await _context.SaveChangesAsync();
                _contextAccessor.HttpContext.Session.SetString("UserEmail", entreprise.Email);
                _contextAccessor.HttpContext.Session.SetString("MotDePasse", entreprise.MotDePasse); // Assuming you have a Nom property
                // Redirect to a different action or return a success message
                return RedirectToAction("Index", "Home"); // Redirects to Home/Index
            }
            return View(entreprise);
        }

        // GET: Entreprises/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entreprise = await _context.Entreprises.FindAsync(id);
            if (entreprise == null)
            {
                return NotFound();
            }
            return View(entreprise);
        }

        // POST: Entreprises/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nom,Email,Facebook,Instagram,officiel,MotDePasse,Adresse,Gouvernourat,tel,tel2,ChampMatricule")] Entreprise entreprise)
        {
            if (id != entreprise.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(entreprise);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EntrepriseExists(entreprise.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(entreprise);
        }

        // GET: Entreprises/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entreprise = await _context.Entreprises
                .FirstOrDefaultAsync(m => m.Id == id);
            if (entreprise == null)
            {
                return NotFound();
            }

            return View(entreprise);
        }

        // POST: Entreprises/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var entreprise = await _context.Entreprises.FindAsync(id);
            if (entreprise != null)
            {
                _context.Entreprises.Remove(entreprise);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EntrepriseExists(int id)
        {
            return _context.Entreprises.Any(e => e.Id == id);
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.ConstrainedExecution;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using webdev_consultationPhotovoltaique.Models.photovoltaiqueDB;

namespace webdev_consultationPhotovoltaique.Controllers
{
    public class UsersController : Controller
    {
        private readonly PhotovoltaiqueDbContext _context;
        private readonly IHttpContextAccessor _contextAccessor;

        public UsersController(PhotovoltaiqueDbContext context, IHttpContextAccessor contextAccessor)
        {
            _context = context;
            _contextAccessor = contextAccessor;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult RegisterUser()
        {
            return View();
        }
        

        // POST: Users/Create
        [HttpPost]
        public ActionResult Create(User user)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Users.Add(user);
                    _context.SaveChanges();
                    _contextAccessor.HttpContext.Session.SetString("UserEmail", user.Email);
                    _contextAccessor.HttpContext.Session.SetString("MotDePasse", user.MotDePasse); // Assuming you have a Nom property
                                                                                                   // Redirect to a different action or return a success message
                    return RedirectToAction("Index", "Home"); // Redirects to Home/Index
                }
                catch (Exception ex)
                {
                    // Log the exception (you can use a logging framework here)
                    var innerException = ex.InnerException?.Message;
                    ViewBag.ErrorMessage = innerException;
                    // Optionally, you can display this error message in the view
                    ModelState.AddModelError("", "Unable to save changes: " + innerException);
                }
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nom,Prénom,Adresse,Télephone,Gouvernourat,Email,MotDePasse")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
        [HttpGet]
        public ActionResult LoginUser()
        {
            
            return View();
        }
        [HttpPost]
        public ActionResult LoginUser(User user)
        {
           
                // Handle the login logic here
                // For example, you can check the credentials against the database
                var userEmail = user.Email;
                var userPassword = user.MotDePasse;
                // Assuming you have a method to validate user credentials
                var isValidUser = ValidateUserCredentials(userEmail, userPassword);

                if (isValidUser)
                {
                _contextAccessor.HttpContext.Session.SetString("UserEmail", user.Email);
                _contextAccessor.HttpContext.Session.SetString("MotDePasse",user.MotDePasse); // Assuming you have a Nom property
                // Redirect to a different action or return a success message
                return RedirectToAction("Index", "Home"); // Redirects to Home/Index
            }
                else
                {
                    // Add an error message to the model state
                    return RedirectToAction("LoginUser");
                }
           
        }

        private bool ValidateUserCredentials(string email, string password)
        {
            // Query the database for a user with the provided email and password
            var user = _context.Users
                               .FirstOrDefault(u => u.Email == email && u.MotDePasse == password);
            
          
                var entreprise = _context.Entreprises
                               .FirstOrDefault(u => u.Email == email && u.MotDePasse == password);
            if (entreprise != null)
            {
                _contextAccessor.HttpContext.Session.SetString("mat", entreprise.ChampMatricule);
            }

            // Return true if a matching user is found, otherwise false
            return user != null || entreprise !=null;
        }
       

        

    }
}

Views/Users/Delete.cshtml
@model webdev_consultationPhotovoltaique.Models.photovoltaiqueDB.User

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prénom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prénom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adresse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Télephone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Télephone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gouvernourat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gouvernourat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MotDePasse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MotDePasse)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Users/Details.cshtml
@model webdev_consultationPhotovoltaique.Models.photovoltaiqueDB.User

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prénom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prénom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adresse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Télephone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Télephone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gouvernourat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gouvernourat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MotDePasse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MotDePasse)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Users/Edit.cshtml
@model webdev_consultationPhotovoltaique.Models.photovoltaiqueDB.User

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prénom" class="control-label"></label>
                <input asp-for="Prénom" class="form-control" />
                <span asp-validation-for="Prénom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Télephone" class="control-label"></label>
                <input asp-for="Télephone" class="form-control" />
                <span asp-validation-for="Télephone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gouvernourat" class="control-label"></label>
                <input asp-for="Gouvernourat" class="form-control" />
                <span asp-validation-for="Gouvernourat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MotDePasse" class="control-label"></label>
                <input asp-for="MotDePasse" class="form-control" />
                <span asp-validation-for="MotDePasse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Users/Index.cshtml
@model IEnumerable<webdev_consultationPhotovoltaique.Models.photovoltaiqueDB.User>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prénom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adresse)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Télephone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gouvernourat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MotDePasse)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prénom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adresse)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Télephone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gouvernourat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MotDePasse)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Users/RegisterUser.cshtml
@model webdev_consultationPhotovoltaique.Models.photovoltaiqueDB.User
@{
    ViewData["Title"] = "Create";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css">
    <link rel="stylesheet" href="~/css/registeruser1.css">
    <title>Ludiflex | Energy</title>
</head>
<body>

    <div class="wrapper">
        <div class="form-box">
            <div class="register2-container" id="register2">
                <div class="top">
                    <header>S'inscrire</header>
                    
                </div>
                <form asp-action="Create" method="post">

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
               
                      
                    <div class="input-box">
                        <input asp-for="Nom" class="input-field" placeholder="Nom" />
                        <span asp-validation-for="Nom" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                       
                        <input asp-for="Prénom" class="input-field" placeholder="Prénom" />
                        <span asp-validation-for="Prénom" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                        
                        <input asp-for="Adresse" class="input-field" placeholder="Adresse" />
                        <span asp-validation-for="Adresse" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                      
                        <input asp-for="Télephone" class="input-field" placeholder="Télephone" />
                        <span asp-validation-for="Télephone" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                       
                        <select asp-for="Gouvernourat" class="input-field">
                            <option value="">Selectionner Gouvernorat</option>
                            <option value="Bizerte">Bizerte</option>
                            <option value="Gabés">Gabés</option>
                            <option value="Gafsa">Gafsa</option>
                            <option value="Jendouba">Jendouba</option>
                            <option value="Kairouan">Kairouan</option>
                            <option value="Kasserine">Kasserine</option>
                            <option value="Kébili">Kébili</option>
                            <option value="Kef">Kef</option>
                            <option value="Mahdia">Mahdia</option>
                            <option value="Manouba">Manouba</option>
                            <option value="Médenine">Médenine</option>
                            <option value="Mounastir">Mounastir</option>
                            <option value="Nabeul">Nabeul</option>
                            <option value="Sfax">Sfax</option>
                            <option value="Sidi Bouzid">Sidi Bouzid</option>
                            <option value="Siliana">Siliana</option>
                            <option value="Sousse">Sousse</option>
                            <option value="Tataouine">Tataouine</option>
                            <option value="Tozeur">Tozeur</option>
                            <option value="Tunis">Tunis</option>
                            <option value="Zaghouan">Zaghouan</option>
                            <option value="Ben arous">Ben arous</option>
                        </select>


                        <span asp-validation-for="Gouvernourat" class="text-danger"></span>

                    </div>
                    <div class="input-box">
                       
                        <input asp-for="Email" class="input-field" placeholder="Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                      
                        <input asp-for="MotDePasse"  class="input-field" placeholder="Mot de Passe" />
                        <span asp-validation-for="MotDePasse" class="text-danger"></span>
                    </div>
                    <div class="input-box">
                        <input type="submit" value="Registrer" class="submit" />
                    </div>
                </form>
                <div class="two-col">
                    <div class="one">
                        <input type="checkbox" id="register-check">
                        <label for="register-check"> Remember Me</label>
                    </div>
                    <div class="two">
                        <a href="@Url.Action("termes","Home")" class="link">Terms & conditions</a></li>
                    </div>
                </div>
              
                <span><a href="@Url.Action("RegisterEntreprise", "Entreprises")" class="link ">S'inscrire en tant qu'entreprise</a></span>
            </div>
        </div>
    </div>

    <script>
        /*document.addEventListener('DOMContentLoaded', () => {
            const registerForm = document.querySelector('.register-container');
            const registerButton = document.querySelector('.submit');
            const rememberMeCheckbox = document.getElementById('register-check');
            const inputs = document.querySelectorAll('.input-field');

            registerButton.addEventListener('click', (event) => {
                event.preventDefault(); // Prevent default form submission

                let isValid = true;

                // Simple validation for each input field
                inputs.forEach(input => {
                    if (input.value.trim() === '') {
                        isValid = false;
                        input.classList.add('error');
                    } else {
                        input.classList.remove('error');
                    }
                });

                if (isValid) {
                    // Collect form data
                    const formData = {};
                    inputs.forEach(input => {
                        formData[input.placeholder] = input.value.trim();
                    });

                    saveFormData(formData);

                    // Here you can handle the form data, for example, send it to a server
                    console.log('Form Data:', formData);
                } else {
                    alert('Please fill in all required fields.');
                }
            });

            function saveFormData(formData) {
                // Handle Remember Me functionality
                if (rememberMeCheckbox.checked) {
                    localStorage.setItem('rememberMe', true);
                    localStorage.setItem('userData', JSON.stringify(formData));
                } else {
                    localStorage.removeItem('rememberMe');
                    localStorage.removeItem('userData');
                }
            }

            // Optional: Add event listeners for input fields to remove error class on input
            inputs.forEach(input => {
                input.addEventListener('input', () => {
                    if (input.value.trim() !== '') {
                        input.classList.remove('error');
                    }
                });
            });

            // Load saved user data if Remember Me was checked
            if (localStorage.getItem('rememberMe')) {
                const savedData = JSON.parse(localStorage.getItem('userData'));
                inputs.forEach(input => {
                    input.value = savedData[input.placeholder] || '';
                });
                rememberMeCheckbox.checked = true;
            }

            // Placeholder function for registering as an enterprise
            window.register2 = function () {
                // You can add functionality here to switch to another registration form
                alert('Switch to enterprise registration form');
            };
        });*/

    </script>
    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }

</body>
</html>